---
title: "DAG"
output: 
  html_document:
    number_sections: true
    code_folding: hide
    toc: true
    toc_float: true
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dagitty)
library(ggdag)
library(ggplot2)
library(tidyverse)
library(ggthemes)

set.seed(123)
```

```{r}
base_dagitty <- dagitty(
'dag {
bb="0,0,1,1"
Age [pos="0.519,0.146"]
BMI [pos="0.356,0.759"]
DM_duration [pos="0.150,0.300"]
GFR [pos="0.900,0.250"]
HbA1c [pos="0.293,0.060"]
Hypertension [pos="0.761,0.083"]
Markers [outcome,pos="0.673,0.707"]
Polineuropathy [pos="0.400,0.400"]
Scales [outcome,pos="0.664,0.435"]
Sex [pos="0.900,0.435"]
Stroke [pos="0.198,0.514"]
Treatment [exposure,pos="0.509,0.548"]
time [pos="0.513,0.664"]
Age -> BMI
Age -> DM_duration
Age -> GFR
Age -> HbA1c
Age -> Hypertension
Age -> Markers
Age -> Scales
Age -> Stroke
BMI -> HbA1c
BMI -> Hypertension
BMI -> Markers
BMI -> Scales
DM_duration -> HbA1c
DM_duration -> Markers
DM_duration -> Polineuropathy
DM_duration -> Scales
DM_duration -> Stroke
GFR -> Markers
GFR -> Scales
HbA1c -> Markers
HbA1c -> Polineuropathy
HbA1c -> Scales
HbA1c -> Stroke
HbA1c <-> Hypertension
Hypertension -> GFR
Hypertension -> Markers
Hypertension -> Scales
Hypertension -> Stroke
Polineuropathy -> Markers
Polineuropathy -> Scales
Sex -> Markers
Sex -> Scales
Stroke -> Markers
Stroke -> Scales
Stroke -> Treatment
Treatment -> Markers
Treatment -> Scales
time -> Markers
time -> Scales
}')
```


```{r}
dag_cand3_gg <- base_dagitty %>% 
  tidy_dagitty(layout = "nicely") %>% 
  # указываем что контролируем
  node_dconnected(controlling_for = c("Age", "Sex", 'Hypertension', 'HbA1c', 'BMI', 'Polineuropathy', 'Stroke', 'DM_duration', 'time', 'GFR'))

```

```{r fig.height=7, fig.width=10}
dag_cand3_gg %>% 
  mutate(adjusted = str_to_title(adjusted),
         # в зависимости от контроял переменной задаем прозрачность стрелок
         arrow = ifelse(adjusted == "Adjusted", 0.25, 0.85),
         # делаем пометки где воздействие а где исход
         label_text = case_when(
           name == exposures(base_dagitty) ~ paste0(name, " \n(Exposure)"),
           name == outcomes(base_dagitty) ~ paste0(name, " \n(Outcome)"), 
           TRUE ~ name),
         # добавляем смещение для аакуратного расположения лейблов названий
         label_nudge_x = case_when(
           name == 'Markers' ~ 0.05,
           name == 'Sex' ~ 0.03,
           name == 'Scales' ~ 0.05,
           name == 'Polineuropathy' ~ 0.08,
           name == 'Treatment' ~ -0.055,
           name == 'Stroke' ~ -0.035,
           name == 'DM_duration' ~ -0.05,
           TRUE ~ 0.02
         ),
         label_nudge_y = case_when(
           name == 'Markers' ~ 0.03,
           name == 'Sex' ~ 0.03,
           name == 'Scales' ~ 0.05,
           name == 'Hypertension' ~ -0.03,
           name == 'Age' ~ 0.03,
           name == 'Polineuropathy' ~ -0.025,
           name == 'HbA1c' ~ -0.025,
           name == 'Treatment' ~ -0.055,
           name == 'DM_duration' ~ 0.01,
           TRUE ~ 0.02
         )) %>% 
  
  
  ggplot(aes(x = x, y = y, xend = xend, yend = yend,
             colour = adjusted, fill = adjusted, shape = adjusted)) +
  # располагаем стрелки и задаем их прозрачность в зависимости от котроля переменной
  geom_dag_edges(aes(edge_alpha = arrow), edge_width = 0.8) +
  # располагаем узлы
  geom_dag_point() +
  # добавляем и располагаем лейблы
  geom_label(
    aes(x = x + label_nudge_x, y = y + label_nudge_y, label = label_text),
    color = "white",
    size = 5,
    label.padding = unit(0.3, "lines"),
    label.r = unit(0.15, "lines"),
    show.legend = FALSE
  )+
  # в зависимости от котроля переменной задаем форму узлов
  scale_shape_manual(values = c(22, 21)) +
  # в зависимости от котроля переменной задаем цвет узлов
  scale_fill_economist() + 
  scale_colour_economist() +
  # белый фон
  theme_dag() +
  theme(
    legend.title = element_blank(),
    legend.text = element_text(size = 15))
```


