---
title: "last_part"
output: html_document
date: "2026-01-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(gtsummary)
library(tidyr)
library(gtsummary)
library(ggplot2)
library(mice)
library(tidyverse)
library(naniar)
library(VIM)
library(tidyverse)
library(gtsummary)
library(flextable)
```

# Descriptive statistic

## Preparations

```{r}
merged_data <- readRDS('clean_data/diabrain.rds')
```

```{r}
merged_data <- merged_data %>% 
  mutate(
    Treatment = factor(Treatment, levels = c('метформин', 'GLP1', 'SGLT2i'))
  ) %>% 
  rename('baseline BMI' = 'BMI 0',
         'baseline HbA1c' = 'HbA1c 0')
```

```{r}
selected_d <- readRDS("clean_data/diabrain.rds") %>%
  select(
    Age, Sex, `HbA1c level`, `DM duration`,
    `HbA1c 0`, `HbA1c 3`, `HbA1c 6`, `HbA1c 9`, `HbA1c 12`,
    `NSE 0`, `NSE 3`, `NSE 6`, `NSE 12`,
    `Lchains 0`, `Lchains 3`, `Lchains 6`, `Lchains 12`,
    `S100 0`, `S100 3`, `S100 6`, `S100 12`,
    `BMI 0`, `BMI 3`, `BMI 6`, `BMI 9`, `BMI 12`,
    `GFR0`, `GFR 6`, `GFR 12`,
    `MOCA 0`, `MOCA 3`, `MOCA 6`, `MOCA 9`, `MOCA 12`,
    `MMSE 0`, `MMSE 3`, `MMSE 6`, `MMSE 9`, `MMSE 12`
  )
```

```{r}
#создаем лист со статистикой для количественных признаков
statistic <- list(
  'NA' = function(x) as.character(sum(is.na(x))),
  'N' = function(x) as.character(sum(!is.na(x))),
  'Mean' = function(x) as.character(round(mean(x, na.rm = TRUE), 1)),
  'Median' = function(x) as.character(round(median(x, na.rm = TRUE), 1)),
  'Sd' = function(x) as.character(round(sd(x, na.rm = TRUE), 2)),
  'Q1-Q3' = function(x) {
    q1 <- round(quantile(x, 0.25, na.rm = TRUE), 1)
    q3 <- round(quantile(x, 0.75, na.rm = TRUE), 1)
    paste0(q1, ' - ', q3)
  },
  'Min-Max' = function(x) {
    min_val <- round(min(x, na.rm = TRUE), 1)
    max_val <- round(max(x, na.rm = TRUE), 1)
    paste0(min_val, ' - ', max_val)
  }
)
```

```{r}
#создаем лист со статистикой для качествеенных признаков
statistic2 <- list(
  'NA' = ~sum(is.na(.x)) %>% as.character(),
  'N' = ~sum(!is.na(.x)) %>% as.character()
  )
```

```{r}
#Функция создания DF по всем перменным (количественные признаки)
allvariablstatic <- function(selection) {
  merged_data %>%
  select(all_of({{selection}})) %>% 
  summarise( 
    across(everything(), statistic)
    ) %>% 
  pivot_longer(everything(), names_to = c('Variable', 'Statistic'), names_sep = '_', values_to = 'Valuetotal') %>% 
    as_grouped_data(groups = 'Variable')
}

#Функция создания DF по группам лечения (количественные признаки)
variablstatic <- function(tratgr, selection) {
  merged_data %>%
  filter(Treatment == {{tratgr}}) %>% 
  select(Treatment, all_of({{selection}})) %>% 
  summarise( 
    across(!Treatment, statistic)
    ) %>% 
  pivot_longer(everything(), names_to = c('Variable', 'Statistic'), names_sep = '_', values_to = 'Valueyes') %>% 
    as_grouped_data(groups = 'Variable')
}


#функция объединения DF
databinding <- function(total, metamorf, GLP1, SGLT2i) {
  {{total}} %>% 
  bind_cols({{GLP1}}[,3]) %>% 
  bind_cols({{metamorf}}[,3]) %>% 
  bind_cols({{SGLT2i}}[,3]) %>% 
  as_grouped_data(groups = 'Variable') %>% 
  filter(!if_all(everything(), is.na))
}

```

## Demography
```{r warning=FALSE, message = FALSE }
#Статистика по демографическим переменным

colsanaliz <- c("Age")

demogrdatatotal <- allvariablstatic(selection = colsanaliz) 
demogrdatametamorf <- variablstatic(tratgr = 'метформин', selection = colsanaliz)
demogrdataGLP1 <- variablstatic(tratgr = 'GLP1', selection = colsanaliz)
demogrdataSGLT2i <- variablstatic(tratgr = 'SGLT2i', selection = colsanaliz)

demogranalisis_col<- databinding(total = demogrdatatotal, metamorf = demogrdatametamorf, 
                            GLP1 = demogrdataGLP1, SGLT2i = demogrdataSGLT2i)


as_flextable(demogranalisis_col) %>% 
  theme_box() %>% 
  bg(part = "header", bg = "cornsilk") %>% 
  bg(i = ~ !is.na(Variable), bg = "grey90", part = "body") %>%
  align(part = 'all', align = 'center') %>% 
  set_header_labels(Valuetotal = 'All', ...4 = 'GLP1', ...5 = 'Metformin', ...6 = 'SGLT2i') %>%
  set_table_properties(layout = 'autofit', width = 0.65) 

```

```{r}
merged_data %>% 
  select(Treatment, Sex) %>% 
  mutate(
    Sex = case_when(
      Sex == '0' ~ 'Female',
      Sex == '1' ~ 'Male',
      TRUE ~ Sex
    ),
    Treatment = case_when(
      Treatment == 'метформин' ~ "Metformin",
      TRUE ~ Treatment
    )
  ) %>% 
  tbl_summary(
    by = Treatment,
    type = all_continuous() ~ "categorical",
    statistic = all_categorical() ~ "{n} ({p}%)")%>% 
  add_overall() %>%
  modify_footnote(everything() ~ NA) %>%
  as_flex_table() %>% 
  theme_box() %>% 
  bg(part = "header", bg = "cornsilk") %>% 
  bg(i = c(1), bg = "grey90", part = "body") %>%
  merge_h_range(i = c(1), j1 = 1, j2 = 5, part = "body") %>%
  align(part = 'all', align = 'center') %>% 
  set_table_properties(layout = 'autofit', width = 0.65)
```
## Diabetes characteristic

```{r warning=FALSE, message = FALSE }
#Статистика по демографическим переменным

colsanaliz <- c("DM duration", 'baseline HbA1c', 'baseline BMI')

diabdatatotal <- allvariablstatic(selection = colsanaliz) 
diabdatametamorf <- variablstatic(tratgr = 'метформин', selection = colsanaliz)
diabdataGLP1 <- variablstatic(tratgr = 'GLP1', selection = colsanaliz)
diabdataSGLT2i <- variablstatic(tratgr = 'SGLT2i', selection = colsanaliz)

diabanalisis_col<- databinding(total = diabdatatotal, metamorf = diabdatametamorf, 
                            GLP1 = diabdataGLP1, SGLT2i = diabdataSGLT2i)


as_flextable(diabanalisis_col) %>% 
  theme_box() %>% 
  bg(part = "header", bg = "cornsilk") %>% 
  bg(i = ~ !is.na(Variable), bg = "grey90", part = "body") %>%
  align(part = 'all', align = 'center') %>% 
  set_header_labels(Valuetotal = 'All', ...4 = 'GLP1', ...5 = 'Metformin', ...6 = 'SGLT2i') %>%
  set_table_properties(layout = 'autofit', width = 0.65) 

```


```{r}
merged_data %>% 
  select(Treatment, `HbA1c level`) %>% 
  mutate(
    `HbA1c level` = case_when(
      `HbA1c level` == '0' ~ 'Appropriate (<7%)',
      `HbA1c level` == '1' ~ 'Inappropriate (>7%)',
      TRUE ~ `HbA1c level`
    ),
    Treatment = case_when(
      Treatment == 'метформин' ~ "Metformin",
      TRUE ~ Treatment
    )
  ) %>% 
  tbl_summary(
    by = Treatment,
    type = all_continuous() ~ "categorical",
    statistic = all_categorical() ~ "{n} ({p}%)")%>% 
  add_overall() %>%
  modify_footnote(everything() ~ NA) %>%
  as_flex_table() %>% 
  theme_box() %>% 
  bg(part = "header", bg = "cornsilk") %>% 
  bg(i = c(1), bg = "grey90", part = "body") %>%
  merge_h_range(i = c(1), j1 = 1, j2 = 5, part = "body") %>%
  align(part = 'all', align = 'center') %>% 
  set_table_properties(layout = 'autofit', width = 0.65)
```



# Паттерны пропущенных значений 

```{r}
naniar::miss_prop_summary(selected_d)
naniar::miss_var_summary(selected_d )
naniar::gg_miss_var(selected_d)
naniar::gg_miss_case(selected_d )
naniar::gg_miss_upset(selected_d )
```


```{r}
naniar::add_any_miss(selected_d) |> 
    gtsummary::tbl_summary(
        by = any_miss_all
    ) |> 
    gtsummary::add_p()
```
```{r fig.width = 8, fig.height = 10, results='asis'}

data_renamed <- selected_d

colnames(data_renamed)[colnames(data_renamed) == "HbA1c 0"] <- "HbA1c_00"
colnames(data_renamed)[colnames(data_renamed) == "HbA1c 3"] <- "HbA1c_03"
colnames(data_renamed)[colnames(data_renamed) == "HbA1c 6"] <- "HbA1c_06"
colnames(data_renamed)[colnames(data_renamed) == "HbA1c 9"] <- "HbA1c_09"
colnames(data_renamed)[colnames(data_renamed) == "HbA1c 12"] <- "HbA1c_12"
vars_of_interest <- c("HbA1c_00", "HbA1c_03", "HbA1c_06", "HbA1c_09", "HbA1c_12")

data_subset <- data_renamed[, vars_of_interest, drop = FALSE]

colnames(data_subset) <- c("Hb_00", "Hb_03", "Hb_06", "Hb_09", "Hb_12")

md_pattern_result <- md.pattern(data_subset, plot = TRUE)
title(main = "Паттерны пропущенных данных HbA1c", 
      line = 2, 
      cex.main = 1.2,
      adj = 0.5)

colnames(md_pattern_result)[1:5] <- c("Месяц 0", "Месяц 3", "Месяц 6", "Месяц 9", "Месяц 12")

print(md_pattern_result)
```
```{r fig.width = 8, fig.height = 10, results='asis'}
data_renamed1 <- selected_d

colnames(data_renamed1)[colnames(data_renamed1) == "NSE 0"] <- "NSE_00"
colnames(data_renamed1)[colnames(data_renamed1) == "NSE 3"] <- "NSE_03"
colnames(data_renamed1)[colnames(data_renamed1) == "NSE 6"] <- "NSE_06"
colnames(data_renamed1)[colnames(data_renamed1) == "NSE 12"] <- "NSE_12"

vars_of_interest1 <- c("NSE_00", "NSE_03", "NSE_06", "NSE_12")

data_subset1 <- data_renamed1[, vars_of_interest1, drop = FALSE]

colnames(data_subset1) <- c("NSE_00", "NSE_03", "NSE_06", "NSE_12")

md_pattern_result1 <- md.pattern(data_subset1, plot = TRUE)
title(main = "Паттерны пропущенных данных NSE", 
      line = 2, 
      cex.main = 1.2,
      adj = 0.5)

colnames(md_pattern_result1)[1:4] <- c("Месяц 0", "Месяц 3", "Месяц 6", "Месяц 12")

print(md_pattern_result1)
```
```{r fig.width = 8, fig.height = 10, results='asis'}
data_renamed2 <- selected_d

colnames(data_renamed2)[colnames(data_renamed2) == "Lchains 0"] <- "Lch_00"
colnames(data_renamed2)[colnames(data_renamed2) == "Lchains 3"] <- "Lch_03"
colnames(data_renamed2)[colnames(data_renamed2) == "Lchains 6"] <- "Lch_06"
colnames(data_renamed2)[colnames(data_renamed2) == "Lchains 12"] <- "Lch_12"

vars_of_interest2 <- c("Lch_00", "Lch_03", "Lch_06", "Lch_12")

data_subset2 <- data_renamed2[, vars_of_interest2, drop = FALSE]

colnames(data_subset2) <- c("Lch_00", "Lch_03", "Lch_06", "Lch_12")

md_pattern_result2 <- md.pattern(data_subset2, plot = TRUE)
title(main = "Паттерны пропущенных данных Lchains", 
      line = 2, 
      cex.main = 1.2,
      adj = 0.5)

colnames(md_pattern_result2)[1:4] <- c("Месяц 0", "Месяц 3", "Месяц 6", "Месяц 12")

print(md_pattern_result2)
```

```{r fig.width = 8, fig.height = 10, results='asis'}
data_renamed3 <- selected_d

colnames(data_renamed3)[colnames(data_renamed3) == "S100 0"] <- "S100_00"
colnames(data_renamed3)[colnames(data_renamed3) == "S100 3"] <- "S100_03"
colnames(data_renamed3)[colnames(data_renamed3) == "S100 6"] <- "S100_06"
colnames(data_renamed3)[colnames(data_renamed3) == "S100 12"] <- "S100_12"

vars_of_interest3 <- c("S100_00", "S100_03", "S100_06", "S100_12")

data_subset3 <- data_renamed3[, vars_of_interest3, drop = FALSE]

colnames(data_subset3) <- c("S100_00", "S100_03", "S100_06", "S100_12")

md_pattern_result3 <- md.pattern(data_subset3, plot = TRUE)
title(main = "Паттерны пропущенных данных S100", 
      line = 2, 
      cex.main = 1.2,
      adj = 0.5)

colnames(md_pattern_result3)[1:4] <- c("Месяц 0", "Месяц 3", "Месяц 6", "Месяц 12")

print(md_pattern_result3)
```
```{r }
selected_d_clean <- selected_d
colnames(selected_d_clean) <- gsub(" ", "_", colnames(selected_d_clean))
imp_clean <- mice(
    selected_d_clean,
    m = 10, 
    maxit = 10, 
    printFlag = FALSE, 
    seed = 42
)

plot(imp_clean)
```




```{r fig.width = 8, fig.height = 10, results='asis'}
bwplot(imp_clean)
```

```{r}
densityplot(imp_clean)
```




